# .github/workflows/frontend.yml
name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: 18 }

      - name: Install & start Backend
        working-directory: backend
        run: |
          npm ci
          npm start &  
          npx wait-on http://localhost:5001/api/health

      - name: Build Frontend
        working-directory: medi-chat-frontend
        env:
          REACT_APP_API_URL: http://localhost:5001
        run: |
          npm ci
          npm run build

      - name: Serve Frontend
        working-directory: medi-chat-frontend
        run: |
          npm install -g serve
          serve -s build -l 3000 &
          npx wait-on http://localhost:3000/medichat

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update -qq
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub \
            | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -qq
          sudo apt-get install -y google-chrome-stable chromium-chromedriver

      - name: Start Selenium server
        run: |
          docker run -d \
            --name selenium \
            --network host \               
            --shm-size=2g \
            selenium/standalone-chrome:4.21.0-20240618
          npx wait-on http://localhost:4444/wd/hub/status

      - name: Run Selenium E2E tests
        working-directory: medi-chat-frontend
        env:
          FRONTEND_URL: http://localhost:3000 
        run: npm run test:e2e

      - name: Docker login & push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build \
            --build-arg REACT_APP_API_URL=http://localhost:5001 \
            -f Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-chatbot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-chatbot:latest
