# .github/workflows/frontend.yml  (at repo root)
name: Frontend CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Install Node 18
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install React deps in the subfolder
      - name: npm install
        working-directory: medi-chat-frontend
        run: npm install

      # 4) Build the React app there
      - name: npm run build
        working-directory: medi-chat-frontend
        run: npm run build

      # 5) Log in to DockerHub
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6) Build & push image using that Dockerfile
      - name: Build & Push Docker image
        run: |
          docker build \
            -f medi-chat-frontend/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-chatbot:latest \
            medi-chat-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-chatbot:latest
