name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: medi-chat-frontend
        run: npm install

      - name: Build React App
        working-directory: medi-chat-frontend
        run: npm run build

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-chatbot:latest \
            medi-chat-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-chatbot:latest
